### ISSUE TITLE
Color-coding by count/percentage

### ISSUE THREAD

**Issue by trafficonese** [nbarrowman/vtree#13]
I'm not sure if its already possible, as there are so many input arguments to `vtree`, but I was looking for color coding the nodes by the relative count from light to more intense.

In this example, the `gender` level fits; 
`male` has 42% and therefore a lighter color than `female` with 58%.
However, the color intensity for the `frame` level only goes from left to right.

I think it would be much easier to interpret the tree if the element with the highest percentage had the most intense color.

```
library(vtree)
library(Hmisc)
getHdata(diabetes)

vtree(diabetes,
      horiz = F,
      c("gender", "frame"))
```

**Comment by nbarrowman** [comment]
I have added a new parameter called `sortfill` (in the develop branch). If you specify `sortfill=TRUE`, nodes will be colored according to the node counts (asuming `gradient=TRUE`, which is the default). For example:

```
library(vtree)
library(Hmisc)
getHdata(diabetes)

vtree(diabetes,
      horiz = F, sortfill = T,
      c("gender", "frame"))
```

But suppose we change the order of gender and frame:

```
vtree(diabetes,
      horiz = F, sortfill = T,
      c("frame", "gender"))
```

Note that female is shown in dark blue except when frame is large, where female appears as light blue, since there are more males with large frame.

**Comment by trafficonese** [comment]
Very awesome addition! Thank you very much.

**Comment by nbarrowman** [comment]
One other note: missing value nodes are still colored white to differentiate them. That doesn't fit with the lightest-to-darkest scheme, so I hope it's not confusing.

**Comment by trafficonese** [comment]
Yeah, but I think that makes sense.
