### ISSUE TITLE
vtree shows the %mv% (missing value) several times inside each leaf node

### ISSUE THREAD

**Issue by sfd99** [nbarrowman/vtree#29]
Hi Nick!

VTREE is truly GREAT!!!

**Q:**

Using your  vtree example R code:

vtree(diabetes,"frame location",horiz=FALSE,height=250,width=850,
  showlevels=FALSE,summary="glyhb \n\nglyhb\nmean=%mean%\nSD=%SD%\nmv=%mv% %leafonly%")

The graph displays well in the Rstudio VIEWER PANE,
but...

vtree shows the **%mv%** (missing value) 
_several times_  (ie: repeated), 
 inside each leaf node!.

Example 1st Leaf Node:

Buckingham
48 (46%)
glyhb
mean=4.7 **mv=2**
SD=1.2 **mv=2**
**mv=2**

See?
**mv=2** is repeated 3 times inside that Node...
Similarly, 
**mv=**  is also repeated in the other leaf nodes.

Help!.
What am I missing?.

**sfd99
San Francisco
R  4.1.2
Rstudio  1.4.1717
Ubuntu Linux 20.04 64bit.
vtree PKG 5.5.3 = development version 
Latest Chromium browser.**

**Comment by nbarrowman** [comment]
Thanks for letting me know. I’ll take a look.

**Comment by nbarrowman** [comment]
vtree has changed a little since I wrote the example (https://rpubs.com/nbarrowman/Data_exploration_with_vtree). Now, by default, the `%mean%` and `%SD%` summary codes also report the number of missing values. There are alternative codes `%meanx%` and `%SDx%` which do not report the number of missing values.

The following command will avoid the repetition:
```
vtree(diabetes,"frame location",horiz=FALSE,height=250,width=850,
showlevels=FALSE,summary="glyhb \n\nglyhb\nmean=%meanx%\nSD=%SDx%\nmv=%mv% %leafonly%")
```

Thanks for the kind word about vtree!

**Comment by sfd99** [comment]
Works perfect - 
Thanks Nick!!.

**PS:** 
 - any webpage(s) 
   with these latest examples / vtree syntax?

**sfd99
San Francisco
R 4.1.2
Rstudio 1.4.1717
Ubuntu Linux 20.04 64bit.
vtree PKG 5.5.3 = development version
Latest Chromium browser.**
